import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "300"],
});

export const metadata: Metadata = {
  title: "Positivus",
  description:
    "Generated by create next app and with programmer Abanob Shenoda",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space_grotesk.className} antialiased flex flex-col h-screen px-3 lg:px-24`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
